version : “3”
services :
  nginx:
    image: nginx:1.17.8
    container_name: nginx_container
    ports:
      - 80:80
    volumes:
      - ./www/data:/nginx/www/data
      - ./nginx/default.conf:/etc/nginx/default.conf
    network_mode: host
